title: azureArchetype
logo: /assets/img/azure-icon.png
description: Home of all things Azure and AI
show_downloads: false
google_analytics: G-WRVZK0VFP4
theme: jekyll-theme-minimal

# Collections
collections:
  links:
    output: false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
markdown: kramdown
highlighter: rouge
