title: azureArchetype
logo: /assets/img/azure-icon.png
description: Home of all things Azure and AI
show_downloads: false
google_analytics: G-WRVZK0VFP4

# Collections
collections:
  links:
    output: false
  checklists:
    output: true
    permalink: /checklists/:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
markdown: kramdown
highlighter: rouge
